[package]
name = "barmd"
description = "The server component for team Î² robotic arm."
version = "0.1.0"
license = "MPL-2.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
fern = { version = "0.7.1", features = ["colored"] }
libm = "0.2.15"
log = "0.4.28"
thiserror = "2.0.17"
